[package]
name = "youtube-adapter-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lib-cockatiel = { path = "../../lib-cockatiel/rust" }
tokio = { version = "1.0", features = ["full"] }
tonic = { version = "0.11", features = ["transport", "tls", "tls-roots"] }
prost = "0.12"
prost-types = "0.12"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
tonic-build = "0.11"
